### ISSUE TITLE
Proxy dead ?

### ISSUE THREAD

**Issue by a5x** [Shiiivx/Kick.com-account-generator#1]
Yo, I use proxies that are valid after passing them through a proxy checker I can't find where the problem comes from

![image](https://github.com/Shiiivx/Kick.com-account-generator/assets/134241855/fa9c00b6-62a1-4f1d-aa0c-b715fc017895)
![image](https://github.com/Shiiivx/Kick.com-account-generator/assets/134241855/1bffb6a1-fc90-4fda-a15a-0f281f2d4db7)

**Comment by Shiiivx** [comment]
Fixed, sorry for the stupid mistake
